# -*- coding: utf-8 -*-
"""1. os. l.mn. -> 2. os. l.poj. trybu rozkazującego.

Domyślnie forma dokonana. Czasowniki opisujące czynność ciągłą (smaż, mieszaj,
gotuj, duś, piecz) zostają niedokonane w rozkazie — inaczej wychodzi
„Usmaż, aż jajka się zetną”, co po polsku jest błędne.
"""
VERBS = {
    "dodajemy": "dodaj",
    "kroimy": "pokrój",
    "gotujemy": "ugotuj",
    "mieszamy": "wymieszaj",
    "układamy": "ułóż",
    "doprawiamy": "dopraw",
    "przekładamy": "przełóż",
    "smarujemy": "posmaruj",
    "blendujemy": "zblenduj",
    "siekamy": "posiekaj",
    "podajemy": "podaj",
    "zjadamy": "zjedz",
    "obieramy": "obierz",
    "podsmażamy": "podsmaż",
    "posypujemy": "posyp",
    "posypujmy": "posyp",
    "zalewamy": "zalej",
    "dusimy": "duś",
    "jemy": "zjedz",
    "myjemy": "umyj",
    "nakładamy": "nałóż",
    "podgrzewamy": "podgrzej",
    "smażymy": "smaż",
    "odstawiamy": "odstaw",
    "odsączamy": "odsącz",
    "pieczemy": "piecz",
    "przygotowujemy": "przygotuj",
    "przyprawiamy": "przypraw",
    "rozgrzewamy": "rozgrzej",
    "wlewamy": "wlej",
    "łączymy": "połącz",
    "dolewamy": "dolej",
    "kładziemy": "połóż",
    "polewamy": "polej",
    "przykrywamy": "przykryj",
    "wsypujemy": "wsyp",
    "dokładamy": "dołóż",
    "dzielimy": "podziel",
    "formujemy": "uformuj",
    "nagrzewamy": "nagrzej",
    "namaczamy": "namocz",
    "obtaczamy": "obtocz",
    "odcedzamy": "odcedź",
    "opiekamy": "opiecz",
    "pijemy": "pij",
    "pomijamy": "pomiń",
    "pozostawiamy": "pozostaw",
    "przygotowaliśmy": "przygotowałeś",
    "przypiekamy": "przypiecz",
    "rozdrabniamy": "rozdrobnij",
    "rozgniatamy": "rozgnieć",
    "składamy": "złóż",
    "studzimy": "ostudź",
    "wbijamy": "wbij",
    "wkładamy": "włóż",
    "wykańczamy": "wykończ",
    "wykładamy": "wyłóż",
    "wypijamy": "wypij",
    "zagotowujemy": "zagotuj",
    "zapiekamy": "zapiecz",
    "zdejmujemy": "zdejmij",
    "zostawiamy": "zostaw",
    "ściągamy": "ściągnij",
    "mamy": "masz",
}
