name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - run: echo "cache_id=$(date +${{ runner.os }}_%Y_%m_%d)" >> $GITHUB_OUTPUT
        id: time

      - uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-build-${{ steps.time.outputs.cache_id }}
          path: .cache
          restore-keys: |
            ${{ runner.os }}-build-

      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force